
package formularies;

import functions.SendEmail;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class FrmCreateAccount extends javax.swing.JFrame {

    SendEmail sendEmail = new SendEmail();
    public FrmCreateAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMainPanelCreateAccount = new javax.swing.JPanel();
        jLbCreateEmail = new javax.swing.JLabel();
        jTfCreateEmail = new javax.swing.JTextField();
        jSpCreateEmail = new javax.swing.JSeparator();
        jLbCreatePassword = new javax.swing.JLabel();
        jPfCreatePassword = new javax.swing.JPasswordField();
        jSpCreatePassword = new javax.swing.JSeparator();
        jBtnVerify = new javax.swing.JPanel();
        jLbVerify = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(290, 200));
        setUndecorated(true);

        jMainPanelCreateAccount.setBackground(new java.awt.Color(255, 255, 255));
        jMainPanelCreateAccount.setForeground(new java.awt.Color(0, 0, 0));
        jMainPanelCreateAccount.setMaximumSize(new java.awt.Dimension(290, 200));
        jMainPanelCreateAccount.setMinimumSize(new java.awt.Dimension(290, 200));
        jMainPanelCreateAccount.setPreferredSize(new java.awt.Dimension(290, 200));
        jMainPanelCreateAccount.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbCreateEmail.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLbCreateEmail.setForeground(new java.awt.Color(1, 97, 112));
        jLbCreateEmail.setText("Correo Electrónico");
        jMainPanelCreateAccount.add(jLbCreateEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTfCreateEmail.setBackground(new java.awt.Color(255, 255, 255));
        jTfCreateEmail.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jTfCreateEmail.setForeground(new java.awt.Color(0, 147, 147));
        jTfCreateEmail.setText("Ingrese su correo electrónico");
        jTfCreateEmail.setBorder(null);
        jTfCreateEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTfCreateEmailFocusGained(evt);
            }
        });
        jTfCreateEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTfCreateEmailMousePressed(evt);
            }
        });
        jTfCreateEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfCreateEmailActionPerformed(evt);
            }
        });
        jMainPanelCreateAccount.add(jTfCreateEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 270, 30));

        jSpCreateEmail.setBackground(new java.awt.Color(1, 97, 112));
        jSpCreateEmail.setForeground(new java.awt.Color(1, 97, 112));
        jSpCreateEmail.setMaximumSize(new java.awt.Dimension(0, 3));
        jSpCreateEmail.setMinimumSize(new java.awt.Dimension(0, 3));
        jMainPanelCreateAccount.add(jSpCreateEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 270, 10));

        jLbCreatePassword.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLbCreatePassword.setForeground(new java.awt.Color(1, 97, 112));
        jLbCreatePassword.setText("Contraseña");
        jLbCreatePassword.setMaximumSize(new java.awt.Dimension(133, 19));
        jLbCreatePassword.setMinimumSize(new java.awt.Dimension(133, 19));
        jLbCreatePassword.setPreferredSize(new java.awt.Dimension(133, 19));
        jMainPanelCreateAccount.add(jLbCreatePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jPfCreatePassword.setBackground(new java.awt.Color(255, 255, 255));
        jPfCreatePassword.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jPfCreatePassword.setForeground(new java.awt.Color(0, 147, 147));
        jPfCreatePassword.setText("****************");
        jPfCreatePassword.setBorder(null);
        jPfCreatePassword.setPreferredSize(new java.awt.Dimension(153, 16));
        jPfCreatePassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPfCreatePasswordFocusGained(evt);
            }
        });
        jPfCreatePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPfCreatePasswordMousePressed(evt);
            }
        });
        jMainPanelCreateAccount.add(jPfCreatePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 270, 30));

        jSpCreatePassword.setBackground(new java.awt.Color(1, 97, 112));
        jSpCreatePassword.setForeground(new java.awt.Color(1, 97, 112));
        jSpCreatePassword.setMaximumSize(new java.awt.Dimension(0, 3));
        jSpCreatePassword.setMinimumSize(new java.awt.Dimension(0, 3));
        jMainPanelCreateAccount.add(jSpCreatePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 270, 10));

        jBtnVerify.setBackground(new java.awt.Color(0, 147, 147));
        jBtnVerify.setForeground(new java.awt.Color(0, 147, 147));
        jBtnVerify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnVerifyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnVerifyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnVerifyMouseExited(evt);
            }
        });

        jLbVerify.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLbVerify.setForeground(new java.awt.Color(255, 255, 255));
        jLbVerify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbVerify.setText("Verificar");

        javax.swing.GroupLayout jBtnVerifyLayout = new javax.swing.GroupLayout(jBtnVerify);
        jBtnVerify.setLayout(jBtnVerifyLayout);
        jBtnVerifyLayout.setHorizontalGroup(
            jBtnVerifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnVerifyLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLbVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jBtnVerifyLayout.setVerticalGroup(
            jBtnVerifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbVerify, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jMainPanelCreateAccount.add(jBtnVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jMainPanelCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jMainPanelCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTfCreateEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTfCreateEmailFocusGained
        jTfCreateEmail.setText("");
    }//GEN-LAST:event_jTfCreateEmailFocusGained
    
    public JPanel getFondo() {
        return jMainPanelCreateAccount;
    }
    private void jTfCreateEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTfCreateEmailMousePressed
        if(jTfCreateEmail.getText().equals("Ingrese su correo electrónico")){
            jTfCreateEmail.setText("");
            jTfCreateEmail.setForeground(new Color(0,147,147));
        }

        if(String.valueOf(jPfCreatePassword.getPassword()).equals("")){
            jPfCreatePassword.setText("****************");
            jPfCreatePassword.setForeground(new Color(0,147,147));
        }
    }//GEN-LAST:event_jTfCreateEmailMousePressed

    private void jTfCreateEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfCreateEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfCreateEmailActionPerformed

    private void jPfCreatePasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPfCreatePasswordFocusGained
        jPfCreatePassword.setText("");
    }//GEN-LAST:event_jPfCreatePasswordFocusGained

    private void jPfCreatePasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPfCreatePasswordMousePressed
        if(jPfCreatePassword.getPassword().equals("****************")){
            jPfCreatePassword.setText("");
            jPfCreatePassword.setForeground(new Color(0,147,147));
        }

        if(String.valueOf(jTfCreateEmail.getText()).equals("")){
            jTfCreateEmail.setText("Ingrese su correo electrónico");
            jTfCreateEmail.setForeground(new Color(0,147,147));
        }
    }//GEN-LAST:event_jPfCreatePasswordMousePressed

    private void jBtnVerifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnVerifyMouseClicked
        JOptionPane.showMessageDialog(this, "Intento de login con los datos:\nUsuario: " + jTfCreateEmail.getText() + "\nContraseña: " + String.valueOf(jPfCreatePassword.getPassword()));
        String email = jTfCreateEmail.getText();
        String temporaryPassword = sendEmail.createEmail(email);
        sendEmail.SendEmail();
    }//GEN-LAST:event_jBtnVerifyMouseClicked

    private void jBtnVerifyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnVerifyMouseEntered
        jBtnVerify.setBackground(new Color(0,224,147));
    }//GEN-LAST:event_jBtnVerifyMouseEntered

    private void jBtnVerifyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnVerifyMouseExited
        jBtnVerify.setBackground(new Color(0,147,147));
    }//GEN-LAST:event_jBtnVerifyMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBtnVerify;
    private javax.swing.JLabel jLbCreateEmail;
    private javax.swing.JLabel jLbCreatePassword;
    private javax.swing.JLabel jLbVerify;
    private javax.swing.JPanel jMainPanelCreateAccount;
    private javax.swing.JPasswordField jPfCreatePassword;
    private javax.swing.JSeparator jSpCreateEmail;
    private javax.swing.JSeparator jSpCreatePassword;
    private javax.swing.JTextField jTfCreateEmail;
    // End of variables declaration//GEN-END:variables
}
