/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularies;

import java.awt.Color;

/**
 *
 * @author hebod
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jBarMenu = new javax.swing.JPanel();
        jBtnClose = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jBtnMin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanelNews = new javax.swing.JPanel();
        jLbNews = new javax.swing.JLabel();
        jPanelinput = new javax.swing.JPanel();
        jPanelProduct = new javax.swing.JPanel();
        jPanelCategory = new javax.swing.JPanel();
        jPanelOutput = new javax.swing.JPanel();
        jPanelUser = new javax.swing.JPanel();
        jPanelOptions = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 560));
        setUndecorated(true);

        jPanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMenu.setForeground(new java.awt.Color(255, 255, 255));
        jPanelMenu.setMaximumSize(new java.awt.Dimension(1080, 560));
        jPanelMenu.setMinimumSize(new java.awt.Dimension(1080, 560));
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBarMenu.setBackground(new java.awt.Color(15, 23, 46));
        jBarMenu.setForeground(new java.awt.Color(15, 23, 46));
        jBarMenu.setMaximumSize(new java.awt.Dimension(1080, 20));
        jBarMenu.setMinimumSize(new java.awt.Dimension(1080, 20));
        jBarMenu.setPreferredSize(new java.awt.Dimension(1080, 20));

        jBtnClose.setBackground(new java.awt.Color(255, 102, 102));
        jBtnClose.setForeground(new java.awt.Color(255, 102, 102));
        jBtnClose.setMaximumSize(new java.awt.Dimension(50, 20));
        jBtnClose.setMinimumSize(new java.awt.Dimension(50, 20));
        jBtnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnCloseMouseExited(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel2.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout jBtnCloseLayout = new javax.swing.GroupLayout(jBtnClose);
        jBtnClose.setLayout(jBtnCloseLayout);
        jBtnCloseLayout.setHorizontalGroup(
            jBtnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jBtnCloseLayout.setVerticalGroup(
            jBtnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnCloseLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jBtnMin.setBackground(new java.awt.Color(1, 97, 112));
        jBtnMin.setForeground(new java.awt.Color(1, 97, 112));
        jBtnMin.setMaximumSize(new java.awt.Dimension(50, 20));
        jBtnMin.setMinimumSize(new java.awt.Dimension(50, 20));
        jBtnMin.setPreferredSize(new java.awt.Dimension(50, 20));
        jBtnMin.setRequestFocusEnabled(false);
        jBtnMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnMinMouseExited(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("-");
        jLabel1.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel1.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout jBtnMinLayout = new javax.swing.GroupLayout(jBtnMin);
        jBtnMin.setLayout(jBtnMinLayout);
        jBtnMinLayout.setHorizontalGroup(
            jBtnMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jBtnMinLayout.setVerticalGroup(
            jBtnMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnMinLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jBarMenuLayout = new javax.swing.GroupLayout(jBarMenu);
        jBarMenu.setLayout(jBarMenuLayout);
        jBarMenuLayout.setHorizontalGroup(
            jBarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBarMenuLayout.createSequentialGroup()
                .addComponent(jBtnMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 980, Short.MAX_VALUE)
                .addComponent(jBtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jBarMenuLayout.setVerticalGroup(
            jBarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBarMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jBarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnMin, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)))
        );

        jPanelMenu.add(jBarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 20));
        jBarMenu.getAccessibleContext().setAccessibleDescription("");

        jPanel1.setBackground(new java.awt.Color(15, 23, 46));
        jPanel1.setForeground(new java.awt.Color(15, 23, 46));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanelNews.setBackground(new java.awt.Color(15, 23, 46));
        jPanelNews.setForeground(new java.awt.Color(15, 23, 46));
        jPanelNews.setToolTipText("");
        jPanelNews.setMaximumSize(new java.awt.Dimension(140, 50));
        jPanelNews.setMinimumSize(new java.awt.Dimension(140, 50));
        jPanelNews.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelNewsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelNewsMouseExited(evt);
            }
        });

        jLbNews.setBackground(new java.awt.Color(255, 255, 255));
        jLbNews.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLbNews.setForeground(new java.awt.Color(255, 255, 255));
        jLbNews.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbNews.setText("Noticias");

        javax.swing.GroupLayout jPanelNewsLayout = new javax.swing.GroupLayout(jPanelNews);
        jPanelNews.setLayout(jPanelNewsLayout);
        jPanelNewsLayout.setHorizontalGroup(
            jPanelNewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbNews, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelNewsLayout.setVerticalGroup(
            jPanelNewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbNews, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelinput.setBackground(new java.awt.Color(35, 112, 47));
        jPanelinput.setForeground(new java.awt.Color(35, 112, 47));
        jPanelinput.setMaximumSize(new java.awt.Dimension(140, 50));
        jPanelinput.setMinimumSize(new java.awt.Dimension(140, 50));

        javax.swing.GroupLayout jPanelinputLayout = new javax.swing.GroupLayout(jPanelinput);
        jPanelinput.setLayout(jPanelinputLayout);
        jPanelinputLayout.setHorizontalGroup(
            jPanelinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanelinputLayout.setVerticalGroup(
            jPanelinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelProduct.setBackground(new java.awt.Color(35, 67, 47));
        jPanelProduct.setForeground(new java.awt.Color(35, 67, 47));
        jPanelProduct.setMaximumSize(new java.awt.Dimension(140, 50));
        jPanelProduct.setMinimumSize(new java.awt.Dimension(140, 50));

        javax.swing.GroupLayout jPanelProductLayout = new javax.swing.GroupLayout(jPanelProduct);
        jPanelProduct.setLayout(jPanelProductLayout);
        jPanelProductLayout.setHorizontalGroup(
            jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelProductLayout.setVerticalGroup(
            jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelCategory.setBackground(new java.awt.Color(100, 67, 47));
        jPanelCategory.setForeground(new java.awt.Color(100, 67, 47));
        jPanelCategory.setMaximumSize(new java.awt.Dimension(140, 50));
        jPanelCategory.setMinimumSize(new java.awt.Dimension(140, 50));
        jPanelCategory.setPreferredSize(new java.awt.Dimension(140, 50));

        javax.swing.GroupLayout jPanelCategoryLayout = new javax.swing.GroupLayout(jPanelCategory);
        jPanelCategory.setLayout(jPanelCategoryLayout);
        jPanelCategoryLayout.setHorizontalGroup(
            jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanelCategoryLayout.setVerticalGroup(
            jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelOutput.setBackground(new java.awt.Color(200, 112, 47));
        jPanelOutput.setForeground(new java.awt.Color(200, 112, 47));
        jPanelOutput.setMaximumSize(new java.awt.Dimension(140, 50));
        jPanelOutput.setMinimumSize(new java.awt.Dimension(140, 50));

        javax.swing.GroupLayout jPanelOutputLayout = new javax.swing.GroupLayout(jPanelOutput);
        jPanelOutput.setLayout(jPanelOutputLayout);
        jPanelOutputLayout.setHorizontalGroup(
            jPanelOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanelOutputLayout.setVerticalGroup(
            jPanelOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelUser.setBackground(new java.awt.Color(200, 200, 47));
        jPanelUser.setForeground(new java.awt.Color(200, 200, 47));
        jPanelUser.setMaximumSize(new java.awt.Dimension(140, 50));
        jPanelUser.setMinimumSize(new java.awt.Dimension(140, 50));
        jPanelUser.setRequestFocusEnabled(false);
        jPanelUser.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanelUserLayout = new javax.swing.GroupLayout(jPanelUser);
        jPanelUser.setLayout(jPanelUserLayout);
        jPanelUserLayout.setHorizontalGroup(
            jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanelUserLayout.setVerticalGroup(
            jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelOptions.setBackground(new java.awt.Color(150, 34, 2));
        jPanelOptions.setForeground(new java.awt.Color(150, 34, 2));
        jPanelOptions.setToolTipText("");
        jPanelOptions.setMaximumSize(new java.awt.Dimension(140, 50));
        jPanelOptions.setMinimumSize(new java.awt.Dimension(140, 50));
        jPanelOptions.setRequestFocusEnabled(false);
        jPanelOptions.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanelOptionsLayout = new javax.swing.GroupLayout(jPanelOptions);
        jPanelOptions.setLayout(jPanelOptionsLayout);
        jPanelOptionsLayout.setHorizontalGroup(
            jPanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanelOptionsLayout.setVerticalGroup(
            jPanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNews, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelinput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jPanelNews, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanelMenu.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, 520));

        jPanel2.setMaximumSize(new java.awt.Dimension(880, 520));
        jPanel2.setMinimumSize(new java.awt.Dimension(880, 520));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jPanelMenu.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 880, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnMinMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_jBtnMinMouseClicked

    private void jBtnMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnMinMouseEntered
        jBtnMin.setBackground(new Color(0,147,147));
    }//GEN-LAST:event_jBtnMinMouseEntered

    private void jBtnMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnMinMouseExited
        jBtnMin.setBackground(new Color(0,97,112));
    }//GEN-LAST:event_jBtnMinMouseExited

    private void jBtnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jBtnCloseMouseClicked

    private void jBtnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCloseMouseEntered
        jBtnClose.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_jBtnCloseMouseEntered

    private void jBtnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCloseMouseExited
        jBtnClose.setBackground(new Color(255,102,102));
    }//GEN-LAST:event_jBtnCloseMouseExited

    private void jPanelNewsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNewsMouseEntered
        jPanelNews.setBackground(new Color(255,255,255));
        jLbNews.setForeground(new Color(15,23,46));
    }//GEN-LAST:event_jPanelNewsMouseEntered

    private void jPanelNewsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNewsMouseExited
        jPanelNews.setBackground(new Color(15,23,46));
        jLbNews.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jPanelNewsMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBarMenu;
    private javax.swing.JPanel jBtnClose;
    private javax.swing.JPanel jBtnMin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLbNews;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCategory;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelNews;
    private javax.swing.JPanel jPanelOptions;
    private javax.swing.JPanel jPanelOutput;
    private javax.swing.JPanel jPanelProduct;
    private javax.swing.JPanel jPanelUser;
    private javax.swing.JPanel jPanelinput;
    // End of variables declaration//GEN-END:variables
}
